default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: blog_app_development
  host: localhost
  username: postgres
  password: pass
  
test:
  <<: *default
  database: blog_app_test
  host: localhost
  username: postgres
  password: pass

production:
  <<: *default
  database: blog_app_production
  host: localhost
  username: postgres
  password: pass
